# Generated by Django 3.2.3 on 2021-06-02 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_bid_comment_listing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='closed_on',
            field=models.DateTimeField(blank=True),
        ),
    ]
